export const colorNames: { [key: string]: string } = {
  "#280000": "Dark Red",
  "#8E0000": "Maroon",
  "#C12923": "Vivid Red",
  "#DA423C": "Crimson",
  "#F45C56": "Coral Red",
  "#FFA8A2": "Peach",
  "#FFCECB": "Blush",
  "#FEEBEA": "Light Pink",
  "#146B43": "Forest Green",
  "#1D965D": "Emerald",
  "#25C178": "Mint Green",
  "#3CDA91": "Light Green",
  "#7EE7B6": "Pale Mint",
  "#BFF3DA": "Light Mint",
  "#D4F7E7": "Very Pale Mint",
  "#EAFBF3": "Off White Green",
  "#272626": "Black",
  "#5A5858": "Dark Gray",
  "#8D8B8B": "Gray",
  "#A2A0A0": "Light Gray",
  "#B3B2B2": "Silver",
  "#D9D8D8": "Very Light Gray",
  "#F1F1F1": "White Smoke",
  "#F8F8F8": "White",
  "#146B17": "Dark Green",
  "#21AB25": "Green",
  "#25C12A": "Bright Green",
  "#3CDA42": "Light Green",
  "#69E26D": "Lime Green",
  "#A9EFAC": "Pale Green",
  "#D4F7D5": "Very Pale Green",
  "#EAFBEA": "Off White Green",
  "#4A3D02": "Brown",
  "#AD8E05": "Golden Brown",
  "#DFB707": "Mustard",
  "#FADD61": "Pale Yellow",
  "#FCEA9C": "Light Yellow",
  "#FDF0B5": "Ivory",
  "#FDF5CE": "Cream",
  "#FEFAE6": "Pale Cream",
  "#143D6B": "Navy Blue",
  "#1D5596": "Royal Blue",
  "#256EC1": "Azure",
  "#3C85DA": "Bright Blue",
  "#7EAFE7": "Sky Blue",
  "#A9CAEF": "Light Blue",
  "#D4E4F7": "Pale Blue",
  "#EAF2FB": "Very Pale Blue",
  "#AE3A04": "Dark Orange",
  "#C74205": "Orange",
  "#F95306": "Bright Orange",
  "#FA773C": "Coral Orange",
  "#FCA983": "Peach",
  "#FDCBB4": "Pale Peach",
  "#FEDDCD": "Very Pale Peach",
  "#FEEEE6": "Light Coral",
};


export const getColorName = (hex: string): string => {
  const upperHex = hex.toUpperCase();
  return colorNames[upperHex] || "";
};
